import type { Metadata } from 'next';
import { pretendard } from '@/styles/font';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'One Brief',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable}`}>{children}</body>
    </html>
  );
}
